from __future__ import annotations

OWASP_RISK_MAP: dict[tuple[str, str], str] = {
    ("workflow", "resume_clear"):       "unrestricted_agency",
    ("workflow", "approval_found"):     "uncontrolled_behavior",
    ("guard", "quality_check"):         "inadequate_sandboxing",
    ("guard", "chat_mode_bypass"):      "inadequate_sandboxing",
    ("guard", "gate_blocked"):          "inadequate_sandboxing",
    ("guard", "branch_stale"):          "broken_trust_boundaries",
    ("guard", "merge_destructive"):     "broken_trust_boundaries",
    ("guard", "label_hygiene"):         "uncontrolled_behavior",
    ("workflow", "step_bypassed"):      "inadequate_sandboxing",
    ("config", "chat_mode_toggle"):     "uncontrolled_behavior",
    ("guard", "chat_mode_guard"):       "inadequate_sandboxing",
    ("guard", "security_tamper"):       "unrestricted_agency",
    ("guard", "workflow_bypass_blocked"): "uncontrolled_behavior",
    ("scm", "git_commit"):              "broken_trust_boundaries",
    ("scm", "git_checkout"):            "broken_trust_boundaries",
    ("scm", "pr_create"):               "broken_trust_boundaries",
    ("scm", "pr_merge"):                "broken_trust_boundaries",
    ("scm", "issue_create"):            "identity_access_abuse",
    ("scm", "issue_close"):             "identity_access_abuse",
    ("scm", "issue_update"):            "identity_access_abuse",
    ("scm", "comment_post"):            "identity_access_abuse",
    ("scm", "label_add"):               "identity_access_abuse",
    ("scm", "label_remove"):            "identity_access_abuse",
    ("scm", "label_swap"):              "identity_access_abuse",
    ("llm", "llm_call"):                "unmonitored_activities",
    ("system", "session_start"):        "unmonitored_activities",
    ("system", "skeleton_build"):       "unmonitored_activities",
    ("system", "skeleton_update"):      "unmonitored_activities",
    ("system", "dashboard_generate"):   "unmonitored_activities",
    ("system", "sequence_extract"):     "unmonitored_activities",
    ("system", "self_check_complete"):  "unmonitored_activities",
    ("system", "self_check_fatal"):     "inadequate_sandboxing",
    ("system", "self_repair"):          "excessive_autonomy",
    ("system", "self_repair_failed"):   "inadequate_sandboxing",
    ("system", "self_check_resolved"):  "inadequate_sandboxing",
    ("system", "agent_start"):          "unmonitored_activities",
    ("system", "session_increment"):    "unmonitored_activities",
    ("health", "doctor_run"):           "unmonitored_activities",
    ("health", "health_run"):           "unmonitored_activities",
    ("health", "health_check_fail"):    "unmonitored_activities",
    ("health", "anomaly_detected"):     "unmonitored_activities",
    ("scm", "pr_exists"):               "unsafe_tool_integration",
    ("scm", "changelog_update"):        "unsafe_tool_integration",
    ("scm", "patch_apply"):             "unsafe_tool_integration",
    ("workflow", "agent_start"):        "excessive_autonomy",
    ("workflow", "healing_run"):        "excessive_autonomy",
    ("workflow", "implement_done"):     "excessive_autonomy",
    ("workflow", "resume_save"):        "excessive_autonomy",
    ("workflow", "resume_load"):        "excessive_autonomy",
    ("eval", "optimizer_run"):          "inadequate_feedback_loops",
    ("eval", "cause"):                  "inadequate_feedback_loops",
    ("config", "config_change"):        "uncontrolled_behavior",
    ("error", "emergency"):             "inadequate_sandboxing",
    ("eval", "ac_test_pass"):           "inadequate_feedback_loops",
    ("eval", "ac_test_fail"):           "inadequate_feedback_loops",
    ("eval", "ac_verify"):              "inadequate_feedback_loops",
    ("eval", "eval_run"):               "inadequate_feedback_loops",
    ("eval", "eval_fail"):              "inadequate_feedback_loops",
    ("eval", "test_run"):               "inadequate_feedback_loops",
    ("eval", "ast_diff"):               "inadequate_feedback_loops",
    ("eval", "llm_quality_check"):      "inadequate_feedback_loops",
    ("guard", "scope_creep_detected"):  "excessive_autonomy",
    ("routing", "routing"):             "opaque_reasoning",
    ("context", "context"):             "opaque_reasoning",
    ("context", "context_build"):       "opaque_reasoning",
    ("context", "architecture_context_load"): "opaque_reasoning",
    ("security", "protection_change"):  "unrestricted_agency",
    ("security", "api_guard_block"):    "unrestricted_agency",
    ("security", "hook_tamper"):        "unrestricted_agency",
    ("security", "env_exposure"):       "identity_access_abuse",
    ("security", "bot_scope_violation"): "identity_access_abuse",
}

OWASP_RISK_CAT_FALLBACK: dict[str, str] = {
    "guard":    "inadequate_sandboxing",
    "llm":      "unmonitored_activities",
    "eval":     "inadequate_feedback_loops",
    "scm":      "broken_trust_boundaries",
    "workflow": "uncontrolled_behavior",
    "system":   "unmonitored_activities",
    "routing":  "opaque_reasoning",
    "context":  "opaque_reasoning",
    "health":   "unmonitored_activities",
    "config":   "unmonitored_activities",
    "perf":     "unmonitored_activities",
    "error":    "unmonitored_activities",
    "security": "unrestricted_agency",
}


def classify(cat: str, evt: str) -> str | None:
    return OWASP_RISK_MAP.get((cat, evt)) or OWASP_RISK_CAT_FALLBACK.get(cat)
